# checkpoints_folder: checkpoints/abo
checkpoints_folder: checkpoints/normalized
checkpoint_file: ckpt.pt
output_dir: data/output_npz/normalized
config_file: config.yaml
device: "cuda"
dataset: abo
dataloader:
  split: train
  batch_size: 128
  num_workers: 4
abo:
  path: "data/ABO/processed-complete"
  use_fps: true
  normalize: true
evaluation:
  resolution: 50 
