# Hydra config for batch evaluation used by superoptim/batch_evaluate_occ.py
source_folder: normalized
small: false
device: cuda

# load bending and tapering
optimization:
  tapering: true
  bending: true

dataloader:
  dataset: ase_object
  batch_size: 256
  num_workers: 4

ase:
  instances_path: /capstor/store/cscs/swissai/a115/data/ase_instances_500
  csv_path: /capstor/store/cscs/swissai/a115/data/ase_wai_train_500/object_info_new.csv
  abo_path: data/ABO/processed-complete
  split: test
  normalize: false

ase_object:
  instances_path: /capstor/store/cscs/swissai/a115/data/ase_instances_500
  csv_path: /capstor/store/cscs/swissai/a115/data/ase_wai_train_500/object_info_new.csv
  abo_path: data/ABO/processed-complete
  split: test
  normalize: false
  gt_params_path: data/output_npz/abo/iou_tb/train.npz