checkpoints_folder: checkpoints/shapenet
checkpoint_file: ckpt.pt
output_dir: data/output_npz/shapenet
config_file: config.yaml
device: "cuda"
dataset: shapenet
dataloader:
  split: test
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
evaluation:
  resolution: 50 