# checkpoints_folder: checkpoints/abo
checkpoints_folder: checkpoints/abo
checkpoint_file: epoch_350.pt
output_dir: data/output_npz/abo_ft
config_file: config.yaml
device: "cuda"
dataset: abo
dataloader:
  split: train
  batch_size: 128
  num_workers: 4
abo:
  path: "data/ABO/processed-complete"
  normalize: false
  categories: null
evaluation:
  resolution: 50 