seed: 42
use_wandb: true
wandb:
  project: superdec
  entity: gtave
run_name: shapenet_iou_051
run_id: .......
dataset: shapenet
device: cuda
checkpoints:
  resume_from: checkpoints/shapenet_iou_051/epoch_900.pt
  keep_epoch: true
superdec:
  extended: true
  rotation6d: false
  decoder:
    n_queries: 16
    n_layers: 3
    n_heads: 1
    masked_attention: false
    swapped_attention: false
    dim_feedforward: 512
    deep_supervision: false
    pos_encoding_type: sinusoidal
  point_encoder:
    in_channels: 3
    out_channels: 128
    kernel_size: 3
    resolution: 32
    voxelization:
      normalize: true
      eps: 0
    l1:
      in_channels: 3
      out_channels: 64
      kernel_size: 3
      resolution: 32
      voxelization:
        normalize: true
        eps: 0
    l2:
      in_channels: 64
      out_channels: 128
      kernel_size: 3
      resolution: 16
      voxelization:
        normalize: true
        eps: 0
    l3:
      in_channels: 128
      out_channels: 128
      kernel_size: 3
      resolution: 16
      voxelization:
        normalize: true
        eps: 0
shapenet:
  path: data/ShapeNet
  categories: null
  normalize: false
  load_occupancy: true
trainer:
  save_path: checkpoints/shapenet_iou_031
  save_every_n_epochs: 100
  num_epochs: 2000
  batch_size: 32
  num_workers: 8
  evaluate_every_n_epochs: 10
  augmentations: true
  occlusions: false
optimizer:
  lr: 0.0004
  weight_decay: 0
  betas:
  - 0.9
  - 0.999
  enable_scheduler: true
  only_heads: false
scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: ${optimizer.lr}
  epochs: ${trainer.num_epochs}
  steps_per_epoch: 240
loss:
  type: iou
  w_sps: 1.2
  w_ext: 0.02
  truncation: 0.05
  w_sdf: 0.2
  w_bbox: 0.2
  w_iou: 0.2
  w_overlap: 5.0
visualization:
  res_primitives: 40
