# Hydra config for batch evaluation used by superoptim/batch_evaluate.py
type: iou
small: false
num_epochs: 1000
device: cuda

optimization:
  tapering: false
  bending: false
  reorient: false
  pruning: false

dataloader:
  dataset: shapenet
  batch_size: 128
  num_workers: 8

shapenet:
  split: test
  path: data/ShapeNet
  categories: null
  load_occupancy: true
  use_fps: true
