# Hydra config for batch evaluation used by superoptim/batch_evaluate.py
type: iou
small: false
num_epochs: 1000
device: cuda

optimization:
  tapering: true
  bending: true
  reorient: false
  pruning: false

dataloader:
  dataset: shapenet
  batch_size: 256
  num_workers: 4

shapenet:
  split: train
  path: data/ShapeNet
  categories: null
  load_occupancy: true
  use_fps: true
